### PR TITLE
Display more of the content in one go

### PR DESCRIPTION
**Pull request by IanMayo**
Initial attempt at resolving #9 

Improve display of list of narrative entries, in both collapsed and expanded modes.
screen shot 2018-03-27 at 21 42 30

screen shot 2018-03-27 at 21 43 09

### CODE REVIEW

**Comment by IanMayo** [comment]
@Morphexe  - would you mind reviewing what I've done here please?

I welcome your guidance on best practice in ReactJS.

**Comment by IanMayo** [comment]
Outstanding issue 1:  when we use Bhumi's bulk generate, the data isn't in the form (name:value) form that the listing renderer expects.  So, while the new "From button" fields are broken down like this:
screen shot 2018-03-28 at 06 47 45

Our renderer tries to break down each letter of the single comment in the bulk-generated lines:
screen shot 2018-03-28 at 06 48 36

I'm pretty sure it just needs the submitted text to be paired as {"Comment", "Lorem.."}  (or something like that.   

@Bhumi, hopefully you can navigate the app to see how/where Eduardo generates his entries, and match it.

**Comment by shahbhumi53** [comment]
hey i did the changes and completed designing, please look at it!
1) http://prntscr.com/ixftkv
-added hanging indentation that is highlighted in the above screenshot
2) http://prntscr.com/ixfua0

**Comment by IanMayo** [comment]
@shahbhumi53 - in the second (collapsed) screenshot, the comment still appears further left than the time value.  This could make it look like each line starts with a comment. Could you sort the alignment so the time value is further left than the comment?

**Comment by shahbhumi53** [comment]
http://prntscr.com/ixgcar

done

**Comment by IanMayo** [comment]
Superceded by #50

**Pull request closed without merging**
